name: Scheduler

on:
  schedule:
    - cron: "20 13 * * *" # Setiap hari pada jam 14:10 waktu Jakarta (UTC+7), yaitu jam 07:10 pagi UTC

jobs:
  run-scheduler:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Call API endpoint
        run: |
          curl -X GET https://digiwarga.vercel.app/run-scheduler
